name: Run Past

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - name: Install dependencies
      run: dart pub get

    - name: Run Script
      run: dart run ./bin/post_past.dart
      env:
        BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        NASA_API_TOKEN: ${{ secrets.NASA_API_TOKEN }}

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Scheduled] Migrate past index"
        commit_user_name: myConsciousness
        commit_user_email: contact@shinyakato.dev
        commit_author: myConsciousness <contact@shinyakato.dev>
